name: Generate Music Recommendation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Run Python script
      env:
        AIML_API_KEY: ${{ secrets.AIML_API_KEY }}
      run: python backend/main.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add output/
        git commit -m "chore: add new music"
        git push origin ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}